// Generated by specta-bindgen

import { my_function as __original_my_function } from './pkg';

export function my_function(name: string): number {
    return __original_my_function(name);
}
// This file has been generated by Specta. DO NOT EDIT.

