[package]
name = "specta-wasm-bindgen"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde-wasm-bindgen = "0.6.5"
specta = { version = "=2.0.0-rc.22", features = ["derive", "function"] }
specta-typescript = "=0.0.9"
wasm-bindgen = "0.2.100"
